# Must be an absolute path to db (no ~/)
db_path = "/home/insipx/.local/share/polkadot/chains/ksmcc3/db"

# Can be set by exporting environment variable "DATABASE_URL" too
psql_url = "postgres://archive:default@localhost/archive"

[[modules]]
name = "System"
keys = [
	"Events",
	"Account"
]

[[modules]]
name = "Democracy"
keys = [
	"PublicPropCount",
	"PublicProps"
]

