[package]
name = "substrate-archive"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
futures = "0.1.26"
tokio = "0.1"
failure = "0.1"
substrate-subxt = { git = "https://github.com/insipx/substrate-subxt", branch = "master" }
jsonrpc-core-client = { version = "13.1.0", features = ["http", "ws"] }
jsonrpc-pubsub = { version = "13.1.0" }
node-primitives = { git = "https://github.com/paritytech/substrate/", package = "node-primitives"}
substrate-rpc = { git = "https://github.com/paritytech/substrate/", package = "substrate-rpc" }
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "substrate-primitives" }
sr-primitives = { git = "https://github.com/paritytech/substrate/", package = "sr-primitives" }
node-runtime = { git = "https://github.com/paritytech/substrate", package = "node-runtime" }
srml-system = { git = "https://github.com/paritytech/substrate", package = "srml-system" }
srml-balances = { git = "https://github.com/paritytech/substrate", package = "srml-balances" }
