[package]
name = "substrate-archive"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4"
env_logger = "0.6"
futures = "0.1.26"
hyper = "0.12"
failure = "0.1"
jsonrpc-core-client = { version = "13.1.0", features = ["http", "ws"] }
jsonrpc-pubsub = { version = "13.1.0" }
node-primitives = { git = "https://github.com/paritytech/substrate/", package = "node-primitives"}
substrate-rpc = { git = "https://github.com/paritytech/substrate/", package = "substrate-rpc" }
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "substrate-primitives" }
sr-primitives = { git = "https://github.com/paritytech/substrate/", package = "sr-primitives" }
