[package]
name = "substrate-archive"
version = "0.2.0-alpha"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4"
futures = { version = "0.3" }
# async-trait = "0.1.26"
failure = "0.1"
chrono = "0.4"
primitive-types = "0.7"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
# enabling arbitrary_precision for serde_json may cause rpc requests to fail
serde_json = "1.0"
r2d2 = "0.8"
dirs = "2"
desub = { git = "https://github.com/paritytech/desub", branch = "master", package="desub-core" }
subxt = { path = "../substrate-subxt", package = "substrate-subxt"}

fern = { version = "0.6", features = ["colored"] }
diesel = { version = "1.4", features = ["postgres", "chrono", "numeric", "r2d2", "serde_json"] }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive", "full"] }

substrate-rpc-primitives = { version = "2.0.0-alpha.5", package = "sp-rpc" }
substrate-primitives = { version = "2.0.0-alpha.5", package = "sp-core" }
runtime-primitives = { version = "2.0.0-alpha.5", package = "sp-runtime" }
runtime-version = { version = "2.0.0-alpha.5", package = "sp-version" }

[dev-dependencies]
async-std = "1.5.0"
desub-extras = { git = "https://github.com/paritytech/desub", branch = "master", package="desub-extras", features = ["polkadot"] }
