[package]
name = "substrate-archive"
version = "0.2.0-alpha.1"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
log = "0.4"
futures = { version = "0.3" }
# async-trait = "0.1.26"
failure = "0.1"
chrono = "0.4"
primitive-types = "0.7"
dotenv = "0.15"
serde = { version = "1.0.105", features = ["derive"] }
# enabling arbitrary_precision for serde_json may cause rpc requests to fail
serde_json = "1.0.50"
dirs = "2"
fern = { version = "0.6", features = ["colored"] }
itertools = "0.9.0"
bastion = "0.3.4"
# Local dependencies
desub = { path = "../desub/core/", package="desub-core" }
subxt = { path = "../substrate-subxt", package = "substrate-subxt"}

kvdb = "0.6"
kvdb-rocksdb = "0.8"
parity-util-mem = "0.6.1"
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive", "full"] }

sp-database = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package="sp-database" }
sc-service = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sc-service" }
sc-client-db = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sc-client-db" }
sp-runtime = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-runtime" }
sc-client-api = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sc-client-api" }
sp-blockchain = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-blockchain" }
sp-state-machine = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-state-machine" }
substrate-rpc-primitives = {  git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-rpc" }
substrate-primitives = {  git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-core" }
runtime-version = {  git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-version" }
sp-arithmetic = { git = "https://github.com/insipx/substrate", branch = "insipx/update-kvdb", package = "sp-arithmetic" }



[dev-dependencies]
async-std = "1.5.0"
desub-extras = { git = "https://github.com/paritytech/desub", branch = "master", package="desub-extras", features = ["polkadot"] }
