[package]
name = "polkadot-archive"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
substrate-archive = { path = "../" }
system = { git = "https://github.com/paritytech/substrate/", package = "srml-system" }
# polkadot-runtime = { git = "https://github.com/paritytech/polkadot", package = "polkadot-runtime", rev="4a983a8" } TEMP
polkadot-runtime = { git = "https://github.com/paritytech/polkadot", package = "polkadot-runtime"}
codec = { package = "parity-scale-codec", version = "1.0.0" }
env_logger = "0.7.0"
