[package]
name = "node-template-archive"
version = "0.2.1"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-archive = { path = "../../", features = ["logging"] }
node-template-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, package = "node-template-runtime" , rev = "35fe3cd1bc4b64cadb0bc6196ae40173db65bb28" }
node-template = { git = "https://github.com/paritytech/substrate", package = "node-template" , rev = "35fe3cd1bc4b64cadb0bc6196ae40173db65bb28" }
clap = { version = "2.33.1", features = ["yaml", "suggestions", "color"] }
toml = "0.5"
futures = "0.3.5"
log = "0.4"
pretty_env_logger = "0.4.0"
anyhow = "1.0.31"
serde = "1.0"
ctrlc = { version = "3.1.5", features = ["termination"] }

[features]
